networks:
  default:
    driver: bridge
    name: grocy

services:
  grocy:
    image: linuxserver/grocy:4.2.0
    container_name: grocy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Lisbon"
    volumes:
      - ~/grocy:/config
    expose:
      - 80
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.grocy.entrypoints=http"
      - "traefik.http.routers.grocy.rule=Host(`grocy.elysium.home`)"