version: '3.3'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
    name: firefly_iii

services:
  app:
    image: fireflyiii/core:version-6.1.19 # set version as variable
    hostname: elysium # variable
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - frontend
      - backend
    ports:
      - 9090:8080
    depends_on:
      - db
    labels: # to be as dynamic as possible
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.entrypoints=http"
      - "traefik.http.routers.firefly.rule=Host(`firefly.elysium.home`)"
      - "traefik.http.routers.firefly.service=firefly"
      - "traefik.http.services.firefly.loadbalancer.server.port=9090"

  db:
    image: postgres:16-alpine # set version as var
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - backend
    volumes:
      - firefly_iii_db:/var/lib/mysql

  cron:
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://elysium:8080/api/v1/cron/REPLACEME\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - backend

volumes:
   firefly_iii_upload:
   firefly_iii_db:
