version: '3.8'

networks:
  default:
    name: reverse-proxy
    driver: bridge
  pihole:
    external: true
  grocy:
    external: true
  firefly_iii:
    external: true
  ha:
    external: true
  media-server:
    external: true

services:
  reverse-proxy:
    image: traefik:v3.1.1
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.plex.address=:32400"
    ports:
      - 80:80
      # - 32400:32400/tcp
    expose:
      - 8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default
      - pihole
      - grocy
      - firefly_iii
      - ha
      - media-server
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.routers.dashboard.entrypoints=http"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.elysium.home`)"
    restart: unless-stopped